# Copyright (c) 2025, 2026 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.

apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: system
data:
  CAPI_VERSION: "${CAPI_VERSION}"
  CAPOCI_VERSION: "${CAPOCI_VERSION}"
  CSR_MACHINE_NAMESPACE: "oci-openshift-autoscaling-operator"
  OCI_TENANCY_ID: "${OCI_TENANCY_ID}"
  OCI_USER_ID: "${OCI_USER_ID}"
  OCI_REGION: "${OCI_REGION}"
  OCI_USE_INSTANCE_PRINCIPAL: "${OCI_USE_INSTANCE_PRINCIPAL}"

  # Autoscaler config
  AUTOSCALER_CPUS: "${AUTOSCALER_CPUS}"
  AUTOSCALER_MEMORY: "${AUTOSCALER_MEMORY}"
  AUTOSCALER_MIN_NODES: "${AUTOSCALER_MIN_NODES}"
  AUTOSCALER_MAX_NODES: "${AUTOSCALER_MAX_NODES}"
  AUTOSCALER_SHAPE: "${AUTOSCALER_SHAPE}"
  AUTOSCALER_DEFINED_TAGS_NAMESPACE: "${AUTOSCALER_DEFINED_TAGS_NAMESPACE}"
  IMAGE_ID: "${IMAGE_ID}"

  # Cluster config 
  COMPARTMENT_ID: "${COMPARTMENT_ID}"

  # Network config
  VCN_ID: "${VCN_ID}"
  OCP_SUBNET_ID: "${OCP_SUBNET_ID}"
  OCP_SUBNET_NAME: "${OCP_SUBNET_NAME}"
  COMPUTE_NSG_NAME: "${COMPUTE_NSG_NAME}"
  NETWORK_SECURITY_GROUP_ID: "${NSG_ID}"
  BARE_METAL_SUBNET_ID: "${BARE_METAL_SUBNET_ID}"
  BARE_METAL_SUBNET_NAME: "${BARE_METAL_SUBNET_NAME}"
  CONTROL_PLANE_ENDPOINT: "${API_LB_IP}"
  API_SERVER_LOAD_BALANCER_ID: "${API_LB_ID}"
  CLUSTER_NETWORK_CIDR_BLOCK: "${CLUSTER_CIDR}"
  SERVICE_NETWORK_CIDR_BLOCK: "${SVC_CIDR}"
