/*
Copyright (c) 2025, 2026 Oracle and/or its affiliates.
Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.
*/

package capoci

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	capiv1alpha1 "github.com/openshift/oci-capi-operator/api/v1alpha1"
	"github.com/openshift/oci-capi-operator/internal/components"
	"github.com/openshift/oci-capi-operator/internal/utils"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"sigs.k8s.io/cluster-api/cmd/clusterctl/api/v1alpha3"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	ctrllog "sigs.k8s.io/controller-runtime/pkg/log"
)

const (
	componentNameCAPOCI                = "CAPOCI"
	infrastructureOCIProviderName      = "oci"
	kindService                        = "Service"
	kindDeployment                     = "Deployment"
	kindServiceAccount                 = "ServiceAccount"
	kindCertificate                    = "Certificate"
	kindIssuer                         = "Issuer"
	kindNamespace                      = "Namespace"
	kindSecret                         = "Secret"
	kindCustomResourceDefinition       = "CustomResourceDefinition"
	kindValidatingWebhookConfiguration = "ValidatingWebhookConfiguration"
	kindMutatingWebhookConfiguration   = "MutatingWebhookConfiguration"
	instancePrincipalValue             = "true"
	enableIMDSArgPrefix                = "--enable-instance-metadata-service-lookup="
	initOCIClientsOnStartupArgPrefix   = "--init-oci-clients-on-startup="
	clusterDNSPolicy                   = "ClusterFirst"
	hostNetworkDNSPolicy               = "ClusterFirstWithHostNet"
	authConfigSecretName               = "capoci-auth-config"
	authConfigTenancyKey               = "tenancy"
	authConfigUserKey                  = "user"
	authConfigRegionKey                = "region"
	authConfigFingerprintKey           = "fingerprint"
	authConfigPrivateKeyKey            = "key"
	authConfigUseInstancePrincipalKey  = "useInstancePrincipal"
	authConfigPassphraseKey            = "passphrase"
)

type CAPOCICredentials struct {
	TenancyID            string `envconfig:"OCI_TENANCY_ID"`
	UserID               string `envconfig:"OCI_USER_ID"`
	Region               string `envconfig:"OCI_REGION"`
	Fingerprint          string `envconfig:"OCI_CREDENTIALS_FINGERPRINT"`
	PrivateKey           string `envconfig:"OCI_CREDENTIALS_KEY"`
	UseInstancePrincipal string `envconfig:"OCI_USE_INSTANCE_PRINCIPAL" default:"false"`
	Passphrase           string `envconfig:"OCI_CREDENTIALS_PASSPHRASE" default:""`
}

type credentialRequirement struct {
	name  string
	value string
}

func (c *CAPOCICredentials) UsesInstancePrincipal() bool {
	if c == nil {
		return false
	}
	useInstancePrincipal, err := parseUseInstancePrincipal(c.UseInstancePrincipal)
	return err == nil && useInstancePrincipal
}

func (c *CAPOCICredentials) Validate() error {
	if c == nil {
		return fmt.Errorf("CAPOCI credentials are required")
	}

	useInstancePrincipal, err := parseUseInstancePrincipal(c.UseInstancePrincipal)
	if err != nil {
		return err
	}

	if useInstancePrincipal {
		return requireCredentialValues("instance-principal auth", []credentialRequirement{
			{name: "OCI_REGION", value: c.Region},
		})
	}

	return requireCredentialValues("key-based auth", []credentialRequirement{
		{name: "OCI_TENANCY_ID", value: c.TenancyID},
		{name: "OCI_USER_ID", value: c.UserID},
		{name: "OCI_REGION", value: c.Region},
		{name: "OCI_CREDENTIALS_FINGERPRINT", value: c.Fingerprint},
		{name: "OCI_CREDENTIALS_KEY", value: c.PrivateKey},
	})
}

func parseUseInstancePrincipal(value string) (bool, error) {
	useInstancePrincipal, err := strconv.ParseBool(strings.TrimSpace(value))
	if err != nil {
		return false, fmt.Errorf("invalid OCI_USE_INSTANCE_PRINCIPAL %q: must be true or false", value)
	}
	return useInstancePrincipal, nil
}

func requireCredentialValues(mode string, values []credentialRequirement) error {
	missing := make([]string, 0, len(values))
	for _, requirement := range values {
		if strings.TrimSpace(requirement.value) == "" {
			missing = append(missing, requirement.name)
		}
	}
	if len(missing) == 0 {
		return nil
	}
	return fmt.Errorf("%s requires %s", mode, strings.Join(missing, ", "))
}

// GetClusterctlComponents returns a list of components for the CAPOCI controller manager
// generated by clusterctl
func GetClusterctlComponents(ctx context.Context, deploymentName string, serviceAccountName string, capociNamespace string, autoscaler *capiv1alpha1.OCIClusterAutoscaler, webhookServiceName string, auth *CAPOCICredentials, scheme *runtime.Scheme, capociProviderVersion string, useHostNetwork bool) ([]unstructured.Unstructured, error) {
	logger := ctrllog.Log.WithName("capoci").WithValues(
		"component", "clusterctl",
		"namespace", capociNamespace,
		"deployment", deploymentName,
		"serviceAccount", serviceAccountName,
		"useHostNetwork", useHostNetwork,
	)
	components, err := utils.GenerateCAPIComponents(ctx, infrastructureOCIProviderName, v1alpha3.InfrastructureProviderType, capociNamespace, capociProviderVersion)
	if err != nil {
		return nil, err
	}
	logger.Info("Fetched CAPOCI clusterctl components", "count", len(components), "version", capociProviderVersion)
	reconcileComponents := []unstructured.Unstructured{}
	for _, component := range components {
		utils.SetDefaultLabels(&component, autoscaler.Name)
		switch component.GetKind() {
		case kindService:
			utils.SetOpenshiftServiceCertAnnotation(&component, webhookServiceName)
			reconcileComponents = append(reconcileComponents, component)
		case kindValidatingWebhookConfiguration, kindMutatingWebhookConfiguration:
			utils.SetOpenshiftCABundleAnnotation(&component)
			reconcileComponents = append(reconcileComponents, component)
		case kindDeployment:
			utils.EditDeploymentCerts(scheme, &component, webhookServiceName)
			if err := setStartupArgs(&component, auth, useHostNetwork); err != nil {
				return nil, fmt.Errorf("failed to configure CAPOCI deployment %q: %w", component.GetName(), err)
			}
			component.SetName(deploymentName)
			reconcileComponents = append(reconcileComponents, component)
		case kindServiceAccount:
			component.SetName(serviceAccountName)
			reconcileComponents = append(reconcileComponents, component)
		case kindCertificate, kindIssuer, kindNamespace, kindSecret, kindCustomResourceDefinition: // skip these
		default:
			reconcileComponents = append(reconcileComponents, component)
		}
	}
	logger.Info("Prepared CAPOCI clusterctl components for reconciliation", "count", len(reconcileComponents))
	return reconcileComponents, nil
}

func setStartupArgs(component *unstructured.Unstructured, auth *CAPOCICredentials, useHostNetwork bool) error {
	if auth == nil {
		return nil
	}
	logger := ctrllog.Log.WithName("capoci").WithValues(
		"component", "deploymentMutation",
		"name", component.GetName(),
		"useHostNetwork", useHostNetwork,
	)

	containers, found, err := unstructured.NestedSlice(component.Object, "spec", "template", "spec", "containers")
	if err != nil {
		return fmt.Errorf("failed to read deployment containers: %w", err)
	}
	if !found || len(containers) == 0 {
		return fmt.Errorf("deployment is missing containers")
	}

	container, ok := containers[0].(map[string]interface{})
	if !ok {
		return fmt.Errorf("deployment container has unexpected type %T", containers[0])
	}

	args, _, err := unstructured.NestedSlice(container, "args")
	if err != nil {
		return fmt.Errorf("failed to read deployment args: %w", err)
	}

	useIMDS := auth.UsesInstancePrincipal()
	args = setOrReplaceArg(args, enableIMDSArgPrefix, strconv.FormatBool(useIMDS))
	if useIMDS {
		// CAPOCI can hang before health endpoints come up when it eagerly initializes
		// OCI clients via IMDS during startup. Defer client initialization instead.
		args = setOrReplaceArg(args, initOCIClientsOnStartupArgPrefix, strconv.FormatBool(false))
	}

	if err := unstructured.SetNestedSlice(container, args, "args"); err != nil {
		return fmt.Errorf("failed to set deployment args: %w", err)
	}
	containers[0] = container
	if err := unstructured.SetNestedSlice(component.Object, containers, "spec", "template", "spec", "containers"); err != nil {
		return fmt.Errorf("failed to write deployment containers: %w", err)
	}
	if err := unstructured.SetNestedField(component.Object, useHostNetwork, "spec", "template", "spec", "hostNetwork"); err != nil {
		return fmt.Errorf("failed to set hostNetwork: %w", err)
	}
	dnsPolicy := clusterDNSPolicy
	if useHostNetwork {
		dnsPolicy = hostNetworkDNSPolicy
	}
	if err := unstructured.SetNestedField(component.Object, dnsPolicy, "spec", "template", "spec", "dnsPolicy"); err != nil {
		return fmt.Errorf("failed to set dnsPolicy: %w", err)
	}
	logger.Info("Configured CAPOCI deployment startup settings",
		"useIMDS", useIMDS,
		"hostNetwork", useHostNetwork,
		"dnsPolicy", dnsPolicy,
		"argCount", len(args),
	)
	return nil
}

func setOrReplaceArg(args []interface{}, prefix, value string) []interface{} {
	target := prefix + value
	for i, arg := range args {
		if s, ok := arg.(string); ok && strings.HasPrefix(s, prefix) {
			args[i] = target
			return args
		}
	}
	return append(args, target)
}

func GetComponents(capociNamespace string, instance *capiv1alpha1.OCIClusterAutoscaler, auth *CAPOCICredentials) *components.Component {
	namespace, namespaceMutateFn := Namespace(capociNamespace, instance)
	authConfigSecret, authConfigSecretMutateFn := AuthConfigSecret(instance, capociNamespace, auth)
	return &components.Component{
		Name: componentNameCAPOCI,
		Subcomponents: components.SubcomponentList{
			{Name: "namespace", Object: namespace, MutateFn: namespaceMutateFn},
			{Name: "authConfigSecret", Object: authConfigSecret, MutateFn: authConfigSecretMutateFn},
		},
	}
}

func Namespace(capociNamespace string, autoscaler *capiv1alpha1.OCIClusterAutoscaler) (client.Object, controllerutil.MutateFn) {
	namespace := &corev1.Namespace{
		ObjectMeta: metav1.ObjectMeta{
			Name: capociNamespace,
		},
	}
	mutateFn := func() error {
		utils.SetDefaultLabels(namespace, autoscaler.Name)
		return nil
	}
	return namespace, mutateFn
}

func AuthConfigSecret(autoscaler *capiv1alpha1.OCIClusterAutoscaler, capociNamespace string, auth *CAPOCICredentials) (client.Object, controllerutil.MutateFn) {
	secret := &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name:      authConfigSecretName,
			Namespace: capociNamespace,
		},
	}

	mutateFn := func() error {
		utils.SetDefaultLabels(secret, autoscaler.Name)
		secret.Data = authConfigData(auth)
		return nil
	}
	return secret, mutateFn
}

func authConfigData(auth *CAPOCICredentials) map[string][]byte {
	if auth == nil {
		return map[string][]byte{}
	}

	data := map[string][]byte{
		authConfigRegionKey:               []byte(auth.Region),
		authConfigUseInstancePrincipalKey: []byte(auth.UseInstancePrincipal),
	}
	if auth.UsesInstancePrincipal() {
		return data
	}

	data[authConfigTenancyKey] = []byte(auth.TenancyID)
	data[authConfigUserKey] = []byte(auth.UserID)
	data[authConfigFingerprintKey] = []byte(auth.Fingerprint)
	data[authConfigPrivateKeyKey] = []byte(auth.PrivateKey)
	if strings.TrimSpace(auth.Passphrase) != "" {
		data[authConfigPassphraseKey] = []byte(auth.Passphrase)
	}
	return data
}
