# Copyright (c) 2025, 2026, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.

apiVersion: capi.openshift.io/v1alpha1
kind: OCIClusterAutoscaler
metadata:
  labels:
    app.kubernetes.io/name: ociclusterautoscaler
    app.kubernetes.io/instance: ociclusterautoscaler
    app.kubernetes.io/part-of: oci-capi-autoscaling-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: oci-capi-autoscaling-operator
  name: ociclusterautoscaler
spec:
  autoscaling:
    minNodes: 0
    maxNodes: 4
    shape: VM.Standard.E5.Flex
    poolIdentifier: vm01
    shapeConfig:
      cpus: 4
      memory: 16
    imageId: ocid1.image.oc1.example.uniqueid
  clusterAutoscaler:
    repositoryURL: https://kubernetes.github.io/autoscaler
    name: oci-cluster-autoscaler
    serviceAccountName: oci-cluster-autoscaler
    cloudProvider: clusterapi
    createRBAC: true
    createServiceAccount: true
