# Copyright (c) 2025, 2026 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.

## Append samples of your project ##
resources:
- capi_v1beta1_ociclusterautoscaler.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
