//go:build !ignore_autogenerated

/*
Copyright (c) 2025, 2026, Oracle and/or its affiliates.
Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingConfig) DeepCopyInto(out *AutoscalingConfig) {
	*out = *in
	if in.MinNodes != nil {
		in, out := &in.MinNodes, &out.MinNodes
		*out = new(int32)
		**out = **in
	}
	if in.MaxNodes != nil {
		in, out := &in.MaxNodes, &out.MaxNodes
		*out = new(int32)
		**out = **in
	}
	if in.ShapeConfig != nil {
		in, out := &in.ShapeConfig, &out.ShapeConfig
		*out = new(ShapeConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingConfig.
func (in *AutoscalingConfig) DeepCopy() *AutoscalingConfig {
	if in == nil {
		return nil
	}
	out := new(AutoscalingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CAPIConfig) DeepCopyInto(out *CAPIConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CAPIConfig.
func (in *CAPIConfig) DeepCopy() *CAPIConfig {
	if in == nil {
		return nil
	}
	out := new(CAPIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAutoscalerConfig) DeepCopyInto(out *ClusterAutoscalerConfig) {
	*out = *in
	if in.CreateRBAC != nil {
		in, out := &in.CreateRBAC, &out.CreateRBAC
		*out = new(bool)
		**out = **in
	}
	if in.CreateServiceAccount != nil {
		in, out := &in.CreateServiceAccount, &out.CreateServiceAccount
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAutoscalerConfig.
func (in *ClusterAutoscalerConfig) DeepCopy() *ClusterAutoscalerConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterAutoscalerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIClusterAutoscaler) DeepCopyInto(out *OCIClusterAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIClusterAutoscaler.
func (in *OCIClusterAutoscaler) DeepCopy() *OCIClusterAutoscaler {
	if in == nil {
		return nil
	}
	out := new(OCIClusterAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCIClusterAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIClusterAutoscalerList) DeepCopyInto(out *OCIClusterAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OCIClusterAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIClusterAutoscalerList.
func (in *OCIClusterAutoscalerList) DeepCopy() *OCIClusterAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(OCIClusterAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCIClusterAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIClusterAutoscalerSpec) DeepCopyInto(out *OCIClusterAutoscalerSpec) {
	*out = *in
	in.Autoscaling.DeepCopyInto(&out.Autoscaling)
	out.CAPI = in.CAPI
	in.ClusterAutoscaler.DeepCopyInto(&out.ClusterAutoscaler)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIClusterAutoscalerSpec.
func (in *OCIClusterAutoscalerSpec) DeepCopy() *OCIClusterAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(OCIClusterAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIClusterAutoscalerStatus) DeepCopyInto(out *OCIClusterAutoscalerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIClusterAutoscalerStatus.
func (in *OCIClusterAutoscalerStatus) DeepCopy() *OCIClusterAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(OCIClusterAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShapeConfig) DeepCopyInto(out *ShapeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShapeConfig.
func (in *ShapeConfig) DeepCopy() *ShapeConfig {
	if in == nil {
		return nil
	}
	out := new(ShapeConfig)
	in.DeepCopyInto(out)
	return out
}
