/*
Copyright (c) 2025, 2026 Oracle and/or its affiliates.
Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.
*/

package crds

import (
	"context"
	"fmt"

	"github.com/openshift/oci-capi-operator/internal/utils"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	v1alpha3 "sigs.k8s.io/cluster-api/cmd/clusterctl/api/v1alpha3"
)

const customResourceDefinitionKind = "CustomResourceDefinition"

// GetClusterctlComponents returns a list of CRDs for the given provider
// generated by clusterctl
func GetClusterctlComponents(ctx context.Context, provider string, providerType v1alpha3.ProviderType, providerVersion string) ([]unstructured.Unstructured, error) {
	components, err := utils.GenerateCAPIComponents(ctx, provider, providerType, "", providerVersion)
	if err != nil {
		return nil, fmt.Errorf("error generating CAPI components: %w", err)
	}
	crds := []unstructured.Unstructured{}
	for _, component := range components {
		switch component.GetKind() {
		case customResourceDefinitionKind:
			utils.SetOpenshiftCABundleAnnotation(&component)
			crds = append(crds, component)
		}
	}
	return crds, nil
}
