/*
Copyright (c) 2025, 2026 Oracle and/or its affiliates.
Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.
*/

package capi

import (
	"context"
	"fmt"

	capiv1alpha1 "github.com/openshift/oci-capi-operator/api/v1alpha1"
	"github.com/openshift/oci-capi-operator/internal/components"
	"github.com/openshift/oci-capi-operator/internal/utils"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"

	securityv1 "github.com/openshift/api/security/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"

	v1alpha3 "sigs.k8s.io/cluster-api/cmd/clusterctl/api/v1alpha3"
)

const (
	componentNameCAPI                  = "CAPI"
	clusterAPIProviderName             = "cluster-api"
	kindService                        = "Service"
	kindDeployment                     = "Deployment"
	kindServiceAccount                 = "ServiceAccount"
	kindCertificate                    = "Certificate"
	kindIssuer                         = "Issuer"
	kindNamespace                      = "Namespace"
	kindSecret                         = "Secret"
	kindCustomResourceDefinition       = "CustomResourceDefinition"
	kindValidatingWebhookConfiguration = "ValidatingWebhookConfiguration"
	kindMutatingWebhookConfiguration   = "MutatingWebhookConfiguration"
	capiSecurityContextConstraintsName = "oci-capi"
	runtimeDefaultSeccompProfile       = "runtime/default"
	systemServiceAccountSubjectFormat  = "system:serviceaccount:%s:%s"
)

// GetClusterctlComponents returns a list of components for the CAPI controller manager
// generated by clusterctl
func GetClusterctlComponents(ctx context.Context, deploymentName string, serviceAccountName string, capiSystemNamespace string, autoscaler *capiv1alpha1.OCIClusterAutoscaler, webhookServiceName string, scheme *runtime.Scheme, providerVersion string) ([]unstructured.Unstructured, error) {
	components, err := utils.GenerateCAPIComponents(ctx, clusterAPIProviderName, v1alpha3.CoreProviderType, capiSystemNamespace, providerVersion)
	if err != nil {
		return nil, err
	}
	reconcileComponents := []unstructured.Unstructured{}

	for _, component := range components {
		utils.SetDefaultLabels(&component, autoscaler.Name)
		switch component.GetKind() {
		case kindService:
			utils.SetOpenshiftServiceCertAnnotation(&component, webhookServiceName)
			reconcileComponents = append(reconcileComponents, component)
		case kindValidatingWebhookConfiguration, kindMutatingWebhookConfiguration:
			utils.SetOpenshiftCABundleAnnotation(&component)
			reconcileComponents = append(reconcileComponents, component)
		case kindDeployment:
			utils.EditDeploymentCerts(scheme, &component, webhookServiceName)
			component.SetName(deploymentName)
			reconcileComponents = append(reconcileComponents, component)
		case kindServiceAccount:
			utils.SetDefaultLabels(&component, autoscaler.Name)
			component.SetName(serviceAccountName)
			reconcileComponents = append(reconcileComponents, component)
		case kindCertificate, kindIssuer, kindNamespace, kindSecret, kindCustomResourceDefinition: // skip these
		default:
			reconcileComponents = append(reconcileComponents, component)
		}
	}
	return reconcileComponents, nil
}

func GetComponents(capiSystemNamespace, capociSystemNamespace, capiServiceAccountName, capociServiceAccountName string, instance *capiv1alpha1.OCIClusterAutoscaler, allowCAPOCIHostNetwork bool) *components.Component {
	capiSCC, capiSCCMutateFn := SecurityContextConstraints(capiSystemNamespace, capociSystemNamespace, capociServiceAccountName, capiServiceAccountName, instance, allowCAPOCIHostNetwork)
	namespace, namespaceMutateFn := CAPINamespace(capiSystemNamespace, instance)

	return &components.Component{
		Name: componentNameCAPI,
		Subcomponents: components.SubcomponentList{
			{Name: "scc", Object: capiSCC, MutateFn: capiSCCMutateFn},
			{Name: "namespace", Object: namespace, MutateFn: namespaceMutateFn},
		},
	}
}

func CAPINamespace(capiSystemNamespace string, instance *capiv1alpha1.OCIClusterAutoscaler) (client.Object, controllerutil.MutateFn) {
	namespace := &corev1.Namespace{
		ObjectMeta: metav1.ObjectMeta{
			Name: capiSystemNamespace,
		},
	}
	mutateFn := func() error {
		utils.SetDefaultLabels(namespace, instance.Name)
		return nil
	}
	return namespace, mutateFn
}

// SecurityContextConstraints defines the SCC for the CAPI manager and CAPOCI controller manager
func SecurityContextConstraints(capiSystemNamespace string, capociSystemNamespace string, capociServiceAccountName string, capiServiceAccountName string, instance *capiv1alpha1.OCIClusterAutoscaler, allowCAPOCIHostNetwork bool) (client.Object, controllerutil.MutateFn) {
	scc := &securityv1.SecurityContextConstraints{
		ObjectMeta: metav1.ObjectMeta{
			Name: capiSecurityContextConstraintsName,
		},
	}

	mutateFn := func() error {
		scc.RunAsUser = securityv1.RunAsUserStrategyOptions{
			Type: securityv1.RunAsUserStrategyRunAsAny,
		}
		scc.SELinuxContext = securityv1.SELinuxContextStrategyOptions{
			Type: securityv1.SELinuxStrategyRunAsAny,
		}
		scc.AllowHostNetwork = allowCAPOCIHostNetwork
		scc.AllowHostPorts = allowCAPOCIHostNetwork
		scc.SeccompProfiles = []string{runtimeDefaultSeccompProfile}
		scc.Users = []string{
			fmt.Sprintf(systemServiceAccountSubjectFormat, capociSystemNamespace, capociServiceAccountName),
			fmt.Sprintf(systemServiceAccountSubjectFormat, capiSystemNamespace, capiServiceAccountName),
		}
		utils.SetDefaultLabels(scc, instance.Name)
		return nil
	}

	return scc, mutateFn
}
